### ISSUE TITLE
loop images crashed app

### ISSUE THREAD

**Issue by ihusak** [seekshiva/react-native-remote-svg#13]
Hello, I have a looping listView with small svg images, when its rendering is ok, but when I start scrolling app isn't responsing and broke. Please help me.
[
![image](https://user-images.githubusercontent.com/8135236/39060930-5e4ded8a-44cb-11e8-8d52-2eac2080d1df.png)
](url)

**Comment by seekshiva** [comment]
@Husak93 It is really a platform limit on how many WebViews can be on a screen at a time. When you scroll fast, lot of browser instances are opened up for each use of the Image component. That was the likely cause of the bug.

If you pretty much know the svg that gets used in the list (like the three svg in your sample code), you could try using `react-native-svg` package. You can define each of the SVG as components and import and use them. That should prevent the crash.

You can use this library if you have remote images that you don't know at the time of development what the image would be (eg, user generated content).

**Comment by Husak93** [comment]
@seekshiva thanks, this works. Youre plugin is cool!
