### ISSUE TITLE
Android SVGs not showing w/ Chrome 72

### ISSUE THREAD

**Issue by zivester** [seekshiva/react-native-remote-svg#30]
Overnight my react-native Android application stopped showing remote svgs using this lib (iOS is fine).  My application was not updated, but other apps were (Chrome from 71 -> 72).  This immediately broke my app and this lib.

I tracked this bug down to WebView, and hopefully others can follow along here: https://github.com/react-native-community/react-native-webview/issues/298

Currently there is no way to downgrade chrome to get it functional again, but identical phones running Chrome 71 do not exhibit this behavior.

**Comment by raen79** [comment]
Apparently converting hex colors to rgb fixes it, I'm trying now

**Comment by zivester** [comment]
@raen79 also confirmed, manually changed one of my remote assets from hex to `rgb()` syntax and it works!  Sick.. now where/when/why in the world did hex stop working...

**Comment by albertogallego** [comment]
Hi guys! How can I reproduce this issue inside the Android studio simulator? Thanks for the solution!

**Comment by zivester** [comment]
Android Webview team confirmed breaking this, with possible workarounds that could be built into this library or upstream in react-native-webview, https://github.com/react-native-community/react-native-webview/issues/298#issuecomment-461109249

**Comment by SamiChab** [comment]
Try to replace every hex code for colors with rgb()
Example: `fill:#ffffff;` => `fill:rgb(255, 255, 255);`

**Comment by manoj-makkuboy** [comment]
Raised a pull request to fix this, meanwhile if you want the fix before release do,
`npm install seekshiva/react-native-remote-svg#pull/33/head`

**Comment by zivester** [comment]
Chrome team has addressed the issue and the fix is now in the Play store as version `72.0.3626.105`.  I just updated and everything is working again for me, so I'm going to close.
