### ISSUE TITLE
SVG images not getting rendered on Android devices

### ISSUE THREAD

**Issue by Nipun16** [seekshiva/react-native-remote-svg#31]
Hi,

Till yesterday, my code was rendering the SVG images on android as well as ios without fail. But suddenly it stopped doing so on android devices. When i tried to investigate, i found a solution of changing the HEX to rgb. I tried it then and there only but unfortunately it didn't click. Can you people please provide me a valid solution as my production app is still breaking.

**Comment by SamiChab** [comment]
Try to replace every hex code for colors with rgb()
Example: `fill:#ffffff;` => `fill:rgb(255, 255, 255);`

**Comment by nishanmmn** [comment]
Have the same issue. 
I changed the code as in merge request "URI encode source HTML of webview #33" and this fixed the issue. 
Please do the merge.

**Comment by manoj-makkuboy** [comment]
Raised a pull request to fix this, meanwhile if you want the fix before release, do
`npm install seekshiva/react-native-remote-svg#pull/33/head`
