### ISSUE TITLE
Rendering text instead of SVG

### ISSUE THREAD

**Issue by Inveth** [seekshiva/react-native-remote-svg#43]
I've tried to use it to render remote SVG images but instead of it it's rendering text :

![text](https://user-images.githubusercontent.com/26462649/56565613-1ce69100-65b1-11e9-9966-a21a58c36ac0.jpg)

```
import Image from 'react-native-remote-svg';
<Image
  source={{
    uri: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px"  viewBox="0 0 100 100">
      <ellipse data-custom-shape="ellipse" cx="50" cy="50" rx="50" ry="50" fill="green"  stroke="#00FF00" stroke-width ="2" />
    </svg>`,
  }}
  style={{ width: 100, height: 100 }}
/>;
```

package.json

```
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "flow": "flow"
  },
  "dependencies": {
    "@react-native-community/netinfo": "^2.0.3",
    "@react-native-community/viewpager": "^1.1.6",
    "babel-eslint": "^10.0.1",
    "bundle": "^2.1.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.6.0",
    "eslint-config-prettier-standard": "^2.0.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.17.1",
    "eslint-plugin-jest": "^22.4.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "eslint-plugin-standard": "^4.0.0",
    "immutable": "^4.0.0-rc.12",
    "lodash": "^4.17.11",
    "prettier": "^1.17.0",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-camera": "^2.4.0",
    "react-native-dropdownalert": "^3.10.0",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-flash-message": "^0.1.11",
    "react-native-modal": "^9.0.0",
    "react-native-orientation-locker": "^1.1.5",
    "react-native-qrcode-scanner": "^1.1.2",
    "react-native-remote-svg": "^2.0.3",
    "react-native-scalable-image": "^0.5.0",
    "react-native-size-matters": "^0.1.7",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.4.0",
    "react-native-swiper": "^1.5.14",
    "react-native-user-inactivity": "^0.1.3-next",
    "react-native-webview": "^5.7.0",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-flow": "^7.0.0",
    "@babel/runtime": "^7.4.3",
    "babel-cli": "^6.26.0",
    "babel-jest": "^24.7.1",
    "babel-preset-flow": "^6.23.0",
    "flow-bin": "^0.96.0",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3",
    "remote-redux-devtools": "^0.5.16"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

What could be the issue here? Is there any conflicts between my packages? I tried to use remote images / local ones and well, just used an example. Same issue all the on all of those.

**Comment by seekshiva** [comment]
@Inveth Chrome 70 introduced a breaking change where directly passing html in url will break and needs to be passed after calling `encodeURIComponent()`. This version was merged as part of https://github.com/seekshiva/react-native-remote-svg/pull/33. 

It looks like the default browser in your device still expects html to be passed directly but `encodeURIComponent()` gets called instead. I'm guessing this must be in android. Can you check and tell what the default browser in your device is, and what version it is running?

**Comment by kuzkokov** [comment]
hi, @seekshiva , I have faced the same issue on android today. my default browser is chrome, v74

**Comment by trta2352** [comment]
@kuzkokov did you manage to resolve the issue. I'm having the same problem.

**Comment by seekshiva** [comment]
It looks like the issue may be happening because the uri string provided contains newline character in it, and that messes up the svg when we do `encodeURIComponent()`. Can you try removing the newline and see if it works? I can provide a fix accordingly.

**Comment by kuzkokov** [comment]
@seekshiva well, actually my case isn't really the same as @Inveth's.
for now, I have my svgs just `required`, but they are resolved into something like `http://localhost:8081/assets/src/...` by `resolveAssetSource` inside your `index.js` and after that, they are correctly fetched inside `SvgImage`.

----------------------------
well, actually, I did some more research. `encodeURIComponent()` create something like this
```
%3Chtml%3E%3Chead%3E%3Cstyle%3Ehtml%2C%20body%20%7B%20margin%3A0%3B%20padding%3A0%3B%20overflow%3Ahidden%3B%20background-color%3A%20transparent%3B%20%7D%20svg%20%7B%20position%3Afixed%3B%20top%3A0%3B%20left%3A0%3B%20height%3A100%25%3B%20width%3A100%25%20%7D%3C%2Fstyle%3E%3C%2
```
but original html is correct, as far as I can see.
and if I remove `encodeURIComponent()` completely, then svg renders almost correctly.

I'm not sure, why do you need this in the first place?

**Comment by kuzkokov** [comment]
@seekshiva made some research. 
Funny thing, chrome team fixed that issue as mentioned [here](https://github.com/react-native-community/react-native-webview/issues/298) and [here](https://github.com/seekshiva/react-native-remote-svg/issues/30) (in this very repository 😄), so now `encodeURIComponent()` just breaking things.
There is still [this issue](https://github.com/seekshiva/react-native-remote-svg/issues/42) appeared if I remove `encodeURIComponent()` from the source code.

**Comment by seekshiva** [comment]
@kuzkokov the scrollbar issue can be fixed by providing `overflow: hidden;` as style to the html or body generated by `SvgImage`. Would it be safe to remove `encodeURIComponent()` otherwise?

**Comment by kuzkokov** [comment]
@seekshiva it seems so. It's only needed if a user has a broken version of chrome, which is from 72 to 72.0.3626.105.

**Comment by seekshiva** [comment]
I've published v2.0.5 that reverts the use of encodeURIComponent as well as adds `overflow: hidden;` to body (html tag already had overflow: hidden) - show hopefully the scrollbar goes away now. Please check and let me know if scrollbar is gone after the update.

**Comment by kuzkokov** [comment]
@seekshiva unfortunately, it didn't help.
I made a [pull request](https://github.com/seekshiva/react-native-remote-svg/pull/44), fixing it. In the separate `react-native-webview` there are props for this purpose. I also added style for `html, body` since I faced a problem that svgs was cropping on android, because html content was bigger than `WebView` itself somehow.
Please check it. Now it's working fine (for me at least 😄).

**Comment by seekshiva** [comment]
Good catch with `showsHorizontalScrollIndicator` and `showsVerticalScrollIndicator`. I've pushed v2.0.6 with your PR.

**Comment by seekshiva** [comment]
@Inveth The above update should solve your issue. Please re-open this issue if you still see the scrollview.
