### ISSUE TITLE
componentWillReceiveProps is deprecated and will be removed in the next major version of RN

### ISSUE THREAD

**Issue by Bruno-Furtado** [seekshiva/react-native-remote-svg#48]
# Feature Request

Use static `getDerivedStateFromProps` instead of `componentWillReceiveProps`.

## Why it is needed

`componentWillReceiveProps` is deprecated and will be removed in the next major version of React Native.

**Comment by mvinet** [comment]
Any update ?

**Comment by waqasxh** [comment]
in SvgImage.js file 
replace
  componentWillReceiveProps(nextProps) {
    const prevUri = this.props.source && this.props.source.uri;
    const nextUri = nextProps.source && nextProps.source.uri;

with
  componentDidUpdate(prevProps) {
    const prevUri = prevProps.source && prevProps.source.uri;
    const nextUri = this.props.source && this.props.source.uri;

**Comment by seekshiva** [comment]
Sorry that this got missed out. I'll need to check on my email notification settings.

I've convert this to a functional component using Hooks and released this at `2.0.9`. Please check this to see if it works without issues.
