### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Xi-gofore** [seekshiva/react-native-remote-svg#57]
I am developing a react-native project. I have the following packages (related with my question) installed:

```
"react-native": "0.63.4",
"react-native-remote-svg": "^2.0.6",
"react-native-webview": "^11.2.1",
...
```

I import the Image component by:
`import Image from 'react-native-remote-svg';
`

I render a remote SVG image by:

```
<Image
          source={{ uri: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/Steps.svg' }}
          style={{ width: winWidth, height: winHeight }}
        />

```
(where the `winWidth` and `winHeight` are the values of my screen width and height)

When I run my app on iOS simulator, I get the following error:

```
[Tue Feb 09 2021 15:32:54.328]  ERROR    Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

This error is located at:
    in RNCWebView (at WebView.ios.js:260)
    in RCTView (at View.js:34)
    in View (at WebView.ios.js:263)
    in WebView (at SvgImage.js:76)
    in RCTView (at View.js:34)
    in View (at SvgImage.js:75)
    in SvgImage (at react-native-remote-svg/index.js:18)
```

**Comment by abel-haj** [comment]
I have got the same issue but on Android!

**Comment by davidverhage** [comment]
I have it running in IOS.
The issue came from not running 'pod install' after adding this element. At least it looks like this.
I rebuild the situation, added the required and before continuing the dev process I ran 'pod install' and the issue seems to have gone.

Possibity for Android is to rebuild but I dont have an android development base to test this for sure.

**Comment by seekshiva** [comment]
`WebView` component used to be provided as part of react-native by default. It was later moved to a separate library called `react-native-webview`.

Now that WebView is in separate library, you need to add that library to your package.json and run `react-native link` so the native code needed for WebView gets linked.

I've added these instructions in ReadMe.
