### ISSUE TITLE
[Android] SVG rendered as text instead of image

### ISSUE THREAD

**Issue by AlbertoMeQ** [seekshiva/react-native-remote-svg#59]
I'm trying to render a remote SVG. I'm on `2.0.6`, Android 12 and Chrome is on version `91.0.4472.114`.

Here is the snippet I'm using:

```
<Image
    source={{ uri: 'https://s3.amazonaws.com/cdn.titanvest.com/misc/car-hex.svg' }}
    style={{ width: 100, height: 100 }} //needs the size
/>
 ```

Even using inlined svg doesn't work:

```
<Image
    source={{
        uri: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px"  viewBox="0 0 100 100">
        <ellipse data-custom-shape="ellipse" cx="50" cy="50" rx="50" ry="50" fill="green"  stroke="#00FF00" stroke-width ="2" />
        </svg>`,
    }}
    style={{ width: 300, height: 300 }}
```

All I get is this:
<img width="240" alt="Screenshot 2022-02-03 at 15 32 40" src="https://user-images.githubusercontent.com/81248192/152363662-0f2ee6ac-9bc1-424e-a0db-1406d3b5cd3d.png">

The same piece of code works perfectly on iOS.

How can I fix it?

**Comment by AlbertoMeQ** [comment]
@seekshiva is this library still being worked on? Just curious to know :)

**Comment by seekshiva** [comment]
Hi @AlbertoMeQ ,

In the inlined svg example, can you remove newline chars from the string and put it in a single string?

Also `#` character acts as uri delimiter. Use `%23` instead of `#` and see if that works.

**Comment by AlbertoMeQ** [comment]
@seekshiva tried this:

```
source={{ uri: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px"  viewBox="0 0 100 100"><ellipse data-custom-shape="ellipse" cx="50" cy="50" rx="50" ry="50" fill="green"  stroke="%2300FF00" stroke-width ="2" /></svg>' }}
```

Still the same text.

**Comment by AlbertoMeQ** [comment]
I managed to fix it by adding the following line of code:

```
androidHardwareAccelerationDisabled={true}
```

in `SvgImage.js`. Another alternative is also changing the parent view to:

```
 <View pointerEvents="none" style={[props.style, props.containerStyle]}
          **renderToHardwareTextureAndroid={true}**>
  ``

In case @seekshiva you want to look into this or for future reference.

**Comment by AlbertoMeQ** [comment]
I submitted a PR (#60) to cover this issue. Let me know @seekshiva

**Comment by AlbertoMeQ** [comment]
@seekshiva Thanks for merging the PR. Do you know when it will be added to npm? So I can update the version on my side :D

**Comment by seekshiva** [comment]
Version 2.0.7 released with the changes.
