### ISSUE TITLE
"react-native": ">=0.57 <0.59"

### ISSUE THREAD

**Issue by waqasxh** [seekshiva/react-native-remote-svg#61]
Any specific reason why we have "react-native": ">=0.57 <0.59" under "peerDependencies" in package.json file

**Comment by algarcia-vector** [comment]
I was unable to install ir by npm i because of this.. 

I am using a mac book pro M1

Also my react native project is version 0.65.2

**Comment by seekshiva** [comment]
This seems to be added at this PR: #36 .

`react-native-webview`'s package.json has a peerDependency on react-native as `*`, so it doesn't make sense to have an upper bound. Will remove this.

**Comment by seekshiva** [comment]
Released `2.0.8` that removes the upper bound on react-native peerDependency.
