### ISSUE TITLE
Double tap zoom

### ISSUE THREAD

**Issue by proutek** [seekshiva/react-native-remote-svg#8]
I'm not able to disable double tap zoom on Android.
I have tried scrollEnabled={false} but it's not working. Any suggestions?

**Comment by seekshiva** [comment]
Can you try wrapping the Image with `<View pointerEvents="none"></View>`? Let me know if it works

**Comment by proutek** [comment]
Yep, it works now.

**Comment by seekshiva** [comment]
Thanks for confirming. I have added `pointerEvents="none"` to the library so that you don't have to manually wrap a View around your images.

Just published v1.2.0 with this fix.
